# Generated by Django 5.1.4 on 2024-12-20 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programID', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=250)),
                ('about', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scholarshipID', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=250)),
                ('about', models.TextField()),
                ('amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('universityID', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=250)),
                ('about', models.TextField()),
                ('website', models.URLField(max_length=250)),
                ('ranking', models.IntegerField(blank=True, null=True)),
                ('programs', models.ManyToManyField(related_name='universities', to='pages.program')),
                ('scholarships', models.ManyToManyField(related_name='universities', to='pages.scholarship')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoolID', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=250)),
                ('fees', models.IntegerField()),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schools', to='pages.university')),
            ],
        ),
    ]
