# Generated by Django 5.1.4 on 2024-12-21 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
